//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCallBackTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCallBackTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   書き込み先フォルダ生成失敗
        ///
        ///%str1% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_CreateDirectoryFailure {
            get {
                return ResourceManager.GetString("Msg_Show_CreateDirectoryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_CreateDirectoryFailure_Caption {
            get {
                return ResourceManager.GetString("Msg_Show_CreateDirectoryFailure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー失敗
        ///
        ///%str1% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_FileCopyFailure {
            get {
                return ResourceManager.GetString("Msg_Show_FileCopyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_FileCopyFailure_Caption {
            get {
                return ResourceManager.GetString("Msg_Show_FileCopyFailure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回収対象のログファイルが見つかりません
        ///
        ///%str1%
        ///%str2% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_LogFileNotFound {
            get {
                return ResourceManager.GetString("Msg_Show_LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Show_LogFileNotFound_Caption {
            get {
                return ResourceManager.GetString("Msg_Show_LogFileNotFound_Caption", resourceCulture);
            }
        }
    }
}
