//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigurationTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ログファイルの保存先を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle_LogFileSave {
            get {
                return ResourceManager.GetString("DialogTitle_LogFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   曲の保存先のフォルダを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle_ScoreDataSaveFolder {
            get {
                return ResourceManager.GetString("DialogTitle_ScoreDataSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語の保存先のフォルダを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle_StoryDataSaveFolder {
            get {
                return ResourceManager.GetString("DialogTitle_StoryDataSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの提出先を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle_SubmissionPath {
            get {
                return ResourceManager.GetString("DialogTitle_SubmissionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ● %str1% に発生した例外 =====
        ///%str2%
        ///このエラーに関する情報を、開発者に問い合わせてください。
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Log_ThreadException {
            get {
                return ResourceManager.GetString("ErrorMsg_Log_ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_CommonCaption {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_CommonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX が正常にインストールされていない可能性があります。
        ///muphic の動作には、DirectX 9.0c が必要です。
        ///
        ///エラーの詳細については、以下のログファイルを参照して下さい。
        ///%str1% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_FailureDirectX {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_FailureDirectX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_FailureDirectX_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_FailureDirectX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   muphic もしくは muphic 動作設定ツールが既に起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_MultipleStartup_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_MultipleStartup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %str1%は、%str2% から %str3% の間の数値を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_NumericUpDown {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_NumericUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な数値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_NumericUpDown_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_NumericUpDown_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。
        ///%str1%
        ///
        ///muphic 動作設定ツールを終了します。
        ///
        ///エラーの詳細については、ログファイル
        ///&quot;%str2%&quot;
        ///を参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Show_ThreadException {
            get {
                return ResourceManager.GetString("ErrorMsg_Show_ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効なディスプレイ アダプタを検出できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form_AdapterSelectComboBox_FailureAdapter {
            get {
                return ResourceManager.GetString("Form_AdapterSelectComboBox_FailureAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このチェックボックスをオンにすると、指定された時間間隔 (分単位) で、作成中の曲や物語が自動的に保存 (バックアップ) されるようになります。何らかの理由で muphic が不具合を起こした場合などでも、作成中の曲や物語が失われるのをある程度防ぐことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_AutoSave {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動保存の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_AutoSave_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_AutoSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このチェックボックスをオンにすると、ものがたりおんがくモードの作曲画面で、ひとりでおんがくモードで作曲した過去の作品を読み込んで使用できるようになります。ですが、ものがたりおんがくモードのコンセプト (物語から連想し作曲する) から外れるため、推奨しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_CanUseSavedScoreInMakeStory {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_CanUseSavedScoreInMakeStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ものがたりおんがくモードでの既存の曲の利用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_CanUseSavedScoreInMakeStory_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_CanUseSavedScoreInMakeStory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各設定項目にマウスポインタを乗せると、ここに説明が表示されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Default {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定項目の説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Default_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それぞれのモードのチェックボックスをオンにすると、そのモードは muphic で選択できなくなります。
        ///授業で muphic を使用する際は、不要なモードのチェックボックスをオンにしておくことで、授業で使用しないモードが選択されてしまうのを防ぐことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_LimitMode {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_LimitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機能の制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_LimitMode_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_LimitMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このチェックボックスをオンにすると、指定したログファイルに muphic の動作に関する情報が保存されるようになります。muphic で何らかのエラーが発生した場合、その詳細や原因なども保存されるため、このログファイルを開発者に送付することで、問題を解決できる場合があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Logging {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ機能の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Logging_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Logging_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   授業で児童が muphic を利用する場合は &quot;授業用 (児童)&quot; に設定することを推奨します。&quot;授業用 (児童)&quot; に設定すると、キーボード操作を無効化したり、不要な機能をオフにすることができ、児童が muphic 誤動作させる危険性を低減できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_OperationMode {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_OperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作モードの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_OperationMode_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_OperationMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このチェックボックスをオンにすると、創作した物語や楽譜が印刷できるようになります。
        ///この機能を利用する際は、プリンタの一覧から印刷に使用するプリンタを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Print {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷機能の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_Print_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_Print_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   muphic で作成した曲や物語の保存先を指定します。無闇に変更すると、これまでの作品が使用できなくなる可能性があるため注意してください。指定された保存先フォルダが存在する場合、&quot;保存先&quot; ラベルが青で表示されます。存在しない場合、設定適用時に作成されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_SavePath {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作品の保存先の指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpText_ConfWindow_SavePath_Title {
            get {
                return ResourceManager.GetString("HelpText_ConfWindow_SavePath_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   動作設定は変更されません。終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ConfirmCancel {
            get {
                return ResourceManager.GetString("Message_Show_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ConfirmCancel_Caption {
            get {
                return ResourceManager.GetString("Message_Show_ConfirmCancel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定されている値をクリアし、初期値に戻します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ConfirmReset {
            get {
                return ResourceManager.GetString("Message_Show_ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ConfirmReset_Caption {
            get {
                return ResourceManager.GetString("Message_Show_ConfirmReset_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作設定が正常に変更されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ReportSave {
            get {
                return ResourceManager.GetString("Message_Show_ReportSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Show_ReportSave_Caption {
            get {
                return ResourceManager.GetString("Message_Show_ReportSave_Caption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon muphicConf {
            get {
                object obj = ResourceManager.GetObject("muphicConf", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
