//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muphic.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PartsLocation : global::System.Configuration.ApplicationSettingsBase {
        
        private static PartsLocation defaultInstance = ((PartsLocation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PartsLocation())));
        
        public static PartsLocation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point OneScr_BackBtn {
            get {
                return ((global::System.Drawing.Point)(this["OneScr_BackBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("615, 66")]
        public global::System.Drawing.Point OneScr_WindowLabel {
            get {
                return ((global::System.Drawing.Point)(this["OneScr_WindowLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("356, 276")]
        public global::System.Drawing.Point TopScr_OneBtn {
            get {
                return ((global::System.Drawing.Point)(this["TopScr_OneBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("586, 276")]
        public global::System.Drawing.Point TopScr_LinkBtn {
            get {
                return ((global::System.Drawing.Point)(this["TopScr_LinkBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("472, 355")]
        public global::System.Drawing.Point TopScr_StoryBtn {
            get {
                return ((global::System.Drawing.Point)(this["TopScr_StoryBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("468, 500")]
        public global::System.Drawing.Point TopScr_EndBtn {
            get {
                return ((global::System.Drawing.Point)(this["TopScr_EndBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 800, 600")]
        public global::System.Drawing.Rectangle MakeStoryScr {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point MakeStoryScr_BackBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_BackBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110, 10")]
        public global::System.Drawing.Point MakeStoryScr_TitleBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_TitleBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("540, 10")]
        public global::System.Drawing.Point MakeStoryScr_SaveBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_SaveBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 10")]
        public global::System.Drawing.Point MakeStoryScr_LoadBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_LoadBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("710, 10")]
        public global::System.Drawing.Point MakeStoryScr_PrintBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PrintBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, 107")]
        public global::System.Drawing.Point MakeStoryScr_CreateNewBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CreateNewBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("702, 65")]
        public global::System.Drawing.Point MakeStoryScr_PlayBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PlayBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("705, 510")]
        public global::System.Drawing.Point MakeStoryScr_CompositionBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CompositionBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 186")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn0 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57, 216")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn1 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 244")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn2 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57, 273")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn3 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57, 357")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn4 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 385")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn5 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57, 414")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn6 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, 443")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn7 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("728, 186")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn8 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 216")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn9 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("728, 244")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn10 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 273")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn11 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 357")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn12 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("728, 385")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn13 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 414")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn14 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("728, 443")]
        public global::System.Drawing.Point MakeStoryScr_CategoryBtn15 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_CategoryBtn15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("520, 500")]
        public global::System.Drawing.Point MakeStoryScr_DeleteBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_DeleteBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("605, 500")]
        public global::System.Drawing.Point MakeStoryScr_AllDeleteBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_AllDeleteBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 550")]
        public global::System.Drawing.Point MakeStoryScr_SentenceBtn {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_SentenceBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183, 87")]
        public global::System.Drawing.Point MakeStoryScr_Thumb0 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Thumb0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("272, 87")]
        public global::System.Drawing.Point MakeStoryScr_Thumb1 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Thumb1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("361, 87")]
        public global::System.Drawing.Point MakeStoryScr_Thumb2 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Thumb2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450, 87")]
        public global::System.Drawing.Point MakeStoryScr_Thumb3 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Thumb3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("539, 87")]
        public global::System.Drawing.Point MakeStoryScr_Thumb4 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Thumb4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127, 88")]
        public global::System.Drawing.Point MakeStoryScr_ThumbLeft {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_ThumbLeft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630, 88")]
        public global::System.Drawing.Point MakeStoryScr_ThumbRight {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_ThumbRight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202, 22")]
        public global::System.Drawing.Point MakeStoryScr_Title {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Title"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("107, 562")]
        public global::System.Drawing.Point MakeStoryScr_Sentence {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_Sentence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 154, 551, 341")]
        public global::System.Drawing.Rectangle MakeStoryScr_PictureArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr_PictureArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 154, 551, 341")]
        public global::System.Drawing.Rectangle MakeStoryScr_BackgroundPlaceArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr_BackgroundPlaceArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 154, 551, 123")]
        public global::System.Drawing.Rectangle MakeStoryScr_BackgroundSkyArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr_BackgroundSkyArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81, 495, 430, 54")]
        public global::System.Drawing.Rectangle MakeStoryScr_StampSelectArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr_StampSelectArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 154")]
        public global::System.Drawing.Point MakeStoryScr_PictureFrameTop {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PictureFrameTop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 473")]
        public global::System.Drawing.Point MakeStoryScr_PictureFrameBottom {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PictureFrameBottom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123, 176")]
        public global::System.Drawing.Point MakeStoryScr_PictureFrameLeft {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PictureFrameLeft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("658, 176")]
        public global::System.Drawing.Point MakeStoryScr_PictureFrameRight {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_PictureFrameRight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn0 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn1 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn2 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn3 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn4 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn5 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn6 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450, 498")]
        public global::System.Drawing.Point MakeStoryScr_StampBtn7 {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_StampBtn7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114, 60, 572, 88")]
        public global::System.Drawing.Rectangle MakeStoryScr_ThumbnailArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["MakeStoryScr_ThumbnailArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("298, 225")]
        public global::System.Drawing.Point SplashWindow_VersionLabel {
            get {
                return ((global::System.Drawing.Point)(this["SplashWindow_VersionLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 800, 600")]
        public global::System.Drawing.Rectangle PlayStoryScr {
            get {
                return ((global::System.Drawing.Rectangle)(this["PlayStoryScr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125, 189, 551, 341")]
        public global::System.Drawing.Rectangle PlayStoryScr_PictureArea {
            get {
                return ((global::System.Drawing.Rectangle)(this["PlayStoryScr_PictureArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point PlayStoryScr_BackBtn {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_BackBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("702, 10")]
        public global::System.Drawing.Point PlayStoryScr_PlayBtn {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_PlayBtn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 568")]
        public global::System.Drawing.Point PlayStoryScr_SentenceCenter {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_SentenceCenter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 51")]
        public global::System.Drawing.Point PlayStoryScr_TitleCenter {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_TitleCenter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 100")]
        public global::System.Drawing.Point PlayStoryScr_StageTop {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_StageTop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 207")]
        public global::System.Drawing.Point PlayStoryScr_StageLeft {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_StageLeft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("652, 207")]
        public global::System.Drawing.Point PlayStoryScr_StageRight {
            get {
                return ((global::System.Drawing.Point)(this["PlayStoryScr_StageRight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 154")]
        public global::System.Drawing.Point MakeStoryScr_SubmitDiag_Anime {
            get {
                return ((global::System.Drawing.Point)(this["MakeStoryScr_SubmitDiag_Anime"]));
            }
        }
    }
}
