//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muphic.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muphic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キミのなまえをおしえてね！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntitleExplain_PlayerName {
            get {
                return ResourceManager.GetString("EntitleExplain_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   きょくの　なまえを　きめよう！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntitleExplain_ScoreTitle {
            get {
                return ResourceManager.GetString("EntitleExplain_ScoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ものがたりに　ぶんしょうを　いれてみよう！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntitleExplain_StorySentence {
            get {
                return ResourceManager.GetString("EntitleExplain_StorySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ものがたりの　だいめいを　きめよう！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntitleExplain_StoryTitle {
            get {
                return ResourceManager.GetString("EntitleExplain_StoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル読み込みエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_ArchiveMgr_Show_FailureArchiveLoad_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_ArchiveMgr_Show_FailureArchiveLoad_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動に必要なファイル %str1% の読み込みに失敗しました。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・muphic が正常にインストールされていない
        /// ・起動に必要なファイルが別のプログラムで使用されている
        ///
        ///エラーの詳細については、ログファイルを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_ArchiveMgr_Show_FailureArchiveLoad_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_ArchiveMgr_Show_FailureArchiveLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス生成エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureCreateDevice_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureCreateDevice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハードウェアアクセラレータ及びリファレンスラスタライザによる DirectX 描画デバイス生成に失敗しました。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・DirectX 9.0c が正しくインストールされていない。
        /// ・ハードウェアが古いか、DirectX に対応していない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureCreateDevice_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureCreateDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureDirectXLoad_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureDirectXLoad_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムの動作に必要なランタイムが不足しています。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・DirectX 9.0c がインストールされていない。
        ///
        ///エラーの詳細については、ログファイルを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureDirectXLoad_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureDirectXLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスプレイモードエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureDisplayMode_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureDisplayMode_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フルスクリーンによる muphic の起動に失敗しました。
        ///
        ///お使いのディスプレイは
        ///解像度 %str1% x %str2%, リフレッシュレート %str3%Hz
        ///に対応していません。
        ///
        ///muphic の設定を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_DrawMgr_Show_FailureDisplayMode_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_DrawMgr_Show_FailureDisplayMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス生成エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_InputMgr_Show_FailureCreateKeyboardDevice_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_InputMgr_Show_FailureCreateKeyboardDevice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectInput キーボードデバイスの生成に失敗しました。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・キーボードデバイスが無効になっている。
        /// 　（あるいは、インストールされていない。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_InputMgr_Show_FailureCreateKeyboardDevice_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_InputMgr_Show_FailureCreateKeyboardDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ● %str1% に発生した例外 =====
        ///%str2%
        ///このエラーに関する情報を、開発者に問い合わせてください。
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_Log_ThreadException {
            get {
                return ResourceManager.GetString("ErrorMsg_Log_ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイル生成エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_LogFileMgr_Show_FailureCreate_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_LogFileMgr_Show_FailureCreate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   muphic ログファイル
        ///&quot;%str1%&quot;
        ///の作成に失敗しました。
        ///
        ///以下の原因である可能性があります。
        /// ・既存ファイルが書き込み禁止になっている。
        /// ・ログファイルのディレクトリへの書き込み権限が無い。
        ///
        ///ロギング機能は使用できませんが、muphic は動作できます。
        ///起動を続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_LogFileMgr_Show_FailureCreate_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_LogFileMgr_Show_FailureCreate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_CheckDirectX_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_CheckDirectX_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムの動作に必要なランタイムが不足しています。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・DirectX 9.0c がインストールされていない。
        ///
        ///エラーの詳細については、ログファイルを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_CheckDirectX_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_CheckDirectX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル読み込みエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_CheckEssentialFiles_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_CheckEssentialFiles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動に必要なファイル以下のファイルが見つからないため、muphic を起動できません。
        ///%str1%
        ///以下の原因である可能性があります。
        /// ・muphic が正常にインストールされていない
        /// ・起動に必要なファイルが別のプログラムで使用されている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_CheckEssentialFiles_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_CheckEssentialFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   muphic 多重起動エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_MultipleStartup {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_MultipleStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   muphic が既に起動されていることを検出しました。
        ///現在動作中の muphic を終了させてから、再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_MultipleStartup_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_MultipleStartup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_ThreadExeption_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_ThreadExeption_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。
        ///%str1%
        ///
        ///muphic を終了します。
        ///エラーの詳細については、ログファイルを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_ThreadExeption_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_ThreadExeption_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_UnhandledException {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。
        ///%str1%
        ///
        ///muphic を終了します。
        ///エラーの詳細については、ログファイルを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_MainWindow_Show_UnhandledException_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_MainWindow_Show_UnhandledException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス生成エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_SoundMgr_Show_FailureCreateDevice_Caption {
            get {
                return ResourceManager.GetString("ErrorMsg_SoundMgr_Show_FailureCreateDevice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectSound デバイスの生成に失敗しました。
        ///muphic を起動できません。
        ///
        ///以下の原因である可能性があります。
        /// ・サウンドデバイスが無効になっている。
        /// 　（あるいは、インストールされていない。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsg_SoundMgr_Show_FailureCreateDevice_Text {
            get {
                return ResourceManager.GetString("ErrorMsg_SoundMgr_Show_FailureCreateDevice_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_SplashWindow {
            get {
                object obj = ResourceManager.GetObject("Image_SplashWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   アーカイブからファイル読込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ArchiveController_ArchivedFileRead_Success {
            get {
                return ResourceManager.GetString("Msg_ArchiveController_ArchivedFileRead_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブ展開失敗 (ファイルが見つからない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ArchiveController_ArchiveFile_NotFound {
            get {
                return ResourceManager.GetString("Msg_ArchiveController_ArchiveFile_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブ展開失敗 (Stream が開けない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ArchiveController_ArchiveFileOpen_Failure {
            get {
                return ResourceManager.GetString("Msg_ArchiveController_ArchiveFileOpen_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブ展開成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ArchiveController_ArchiveFileOpen_Success {
            get {
                return ResourceManager.GetString("Msg_ArchiveController_ArchiveFileOpen_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル &quot;%str1%&quot; の読込に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_ArchiveController_ArchiveFileOpenFailureException {
            get {
                return ResourceManager.GetString("Msg_ArchiveController_ArchiveFileOpenFailureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面遷移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Common_ScreenTransition {
            get {
                return ResourceManager.GetString("Msg_Common_ScreenTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作曲時の音階制限機能が無効化されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_CodeLimitMode_OFF {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_CodeLimitMode_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作曲時の音階制限機能が有効になりました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_CodeLimitMode_ON {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_CodeLimitMode_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   題名入力画面 -&gt; 作曲画面 (曲名入力完了 &quot;%str1%&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_EndEntitle {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_EndEntitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽譜画面 -&gt; 作曲画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_EndShowScore {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_EndShowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作曲画面 -&gt; 題名入力画面 (曲名入力開始) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_StartEntitle {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_StartEntitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作曲画面 -&gt; 楽譜画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_CompositionScr_StartShowScore {
            get {
                return ResourceManager.GetString("Msg_CompositionScr_StartShowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り替え失敗 (%str1%モード -&gt; %str2%モード) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_ChangeIsWindow_Failure {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_ChangeIsWindow_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り替え (%str1%モード -&gt; %str2%モード) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_ChangeIsWindow_Success {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_ChangeIsWindow_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX -Direct3D デバイス生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX -ディスプレイ表示モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice_DisplayMode {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (DirectX 9.0cがインストールされていないか、ハードウェア未対応のため、muphicを起動できませんでした) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice_Failure {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハードウェアアクセラレータ及びハードウェア頂点処理 (最上位のパフォーマンスです) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice_HH {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice_HH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハードウェアアクセラレータ及びソフトウェア頂点処理 (中程度のパフォーマンスです) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice_HS {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice_HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リファレンスラスタライザ及びソフトウェア頂点処理 (最も低いパフォーマンスです) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_CreateDevice_SS {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_CreateDevice_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全画面表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_FullScreenMode {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_FullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テクスチャファイル ロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_LoadTextureFile {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_LoadTextureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込済みのためスキップ &quot;%str1%&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_LoadTextureFile_Failure_Reason_Loaded {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_LoadTextureFile_Failure_Reason_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (テクスチャファイル %str1% は存在しない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_LoadTextureFile_Failure_Reason_NotExist {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_LoadTextureFile_Failure_Reason_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テクスチャファイル %str1% がアーカイブ内に存在しないため、読み込みに失敗しました。アーカイブと muphic のバージョンが一致していない可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_LoadTextureFile_Failure_Reason_NotExist_ {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_LoadTextureFile_Failure_Reason_NotExist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス再生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_ResetDevice {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %str1% ミリ秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_TextureLoadTime {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_TextureLoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_TextureLoadTime_Title {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_TextureLoadTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   統合画像ファイル (png+txt) 解放 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_UnloadTextureFile {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_UnloadTextureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (テクスチャファイル %str1% は存在しない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_UnloadTextureFile_Failure_Reason_NotExist {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_UnloadTextureFile_Failure_Reason_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (テクスチャファイル %str1% は読み込まれていない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_UnloadTextureFile_Failure_Reason_Unloaded {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_UnloadTextureFile_Failure_Reason_Unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_DrawMgr_WindowMode {
            get {
                return ResourceManager.GetString("Msg_DrawMgr_WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動後 %str1% 分経過 -- 推定メモリ使用量 %str2% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_FrameMgr_CheckUsedMemory {
            get {
                return ResourceManager.GetString("Msg_FrameMgr_CheckUsedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX -DirectInput デバイス生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_InputMgr_CreateKeyboardDevice {
            get {
                return ResourceManager.GetString("Msg_InputMgr_CreateKeyboardDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (キーボードがインストールされてない等の原因により、muphic を起動できませんでした) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_InputMgr_CreateKeyboardDevice_Failure {
            get {
                return ResourceManager.GetString("Msg_InputMgr_CreateKeyboardDevice_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーボード: 協調レベル設定 (完了) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_InputMgr_CreateKeyboardDevice_Success {
            get {
                return ResourceManager.GetString("Msg_InputMgr_CreateKeyboardDevice_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロギング終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LogfileMgr_EndLogging {
            get {
                return ResourceManager.GetString("Msg_LogfileMgr_EndLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===================================================================
        ///  muphic ログファイル  -- System Version %str1%
        ///===================================================================
        ///※先頭に $ が付いているメッセージは Debug ビルド時のみのメッセージです。Release ビルド時は出力されません。
        ///※先頭に # ERROR # が付いているメッセージがある場合、何らかのエラーが発生しています。システム開発者に問い合わせてください。
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LogfileMgr_LogfileHeader {
            get {
                return ResourceManager.GetString("Msg_LogfileMgr_LogfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロギング開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LogFileMgr_StartLogging {
            get {
                return ResourceManager.GetString("Msg_LogFileMgr_StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LogfileMgr_Uptime {
            get {
                return ResourceManager.GetString("Msg_LogfileMgr_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_ButtonClick {
            get {
                return ResourceManager.GetString("Msg_MainWindow_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多重起動チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_CheckMultipleStartup {
            get {
                return ResourceManager.GetString("Msg_MainWindow_CheckMultipleStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mutex 所有権取得失敗 ::: muphic 起動済みのためプログラム終了
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_CheckMultipleStartup_Failure {
            get {
                return ResourceManager.GetString("Msg_MainWindow_CheckMultipleStartup_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mutex 初期所有権取得 ::: muphic 起動処理開始
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_CheckMultipleStartup_Success {
            get {
                return ResourceManager.GetString("Msg_MainWindow_CheckMultipleStartup_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_KeyPress {
            get {
                return ResourceManager.GetString("Msg_MainWindow_KeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt + Enter（表示モード切替） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_KeyPress_AltEnter {
            get {
                return ResourceManager.GetString("Msg_MainWindow_KeyPress_AltEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client 動作のため、キーボード操作はブロックされます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_KeyPress_Block {
            get {
                return ResourceManager.GetString("Msg_MainWindow_KeyPress_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escape (プログラム終了) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_KeyPress_Esc {
            get {
                return ResourceManager.GetString("Msg_MainWindow_KeyPress_Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_KeyPress_ShiftKey {
            get {
                return ResourceManager.GetString("Msg_MainWindow_KeyPress_ShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動フェーズ完了, メインループ開始
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_StartupPhase_Complete {
            get {
                return ResourceManager.GetString("Msg_MainWindow_StartupPhase_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーム上でハンドルされない例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_ThreadExeption {
            get {
                return ResourceManager.GetString("Msg_MainWindow_ThreadExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションでハンドルされない例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MainWindow_UnhandledException {
            get {
                return ResourceManager.GetString("Msg_MainWindow_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語データ 自動保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_AutoSave {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動保存データ削除 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_AutoSaveFileDelete_Failure {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_AutoSaveFileDelete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提出作品管理画面 -&gt; 物語作成画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_CloseStoryExplorer {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_CloseStoryExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作曲画面 -&gt; 物語作成画面 (ページ %str1% 作曲終了) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_EndComposition {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_EndComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   題名入力画面 -&gt; 物語作成画面 (物語名入力完了 &quot;%str1%&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_EndEntitle {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_EndEntitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文章入力画面 -&gt; 物語作成画面 )ページ %str1% 文章入力完了 &quot;%str2%&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_EndInputSentence {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_EndInputSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語再生画面 -&gt; 物語作成画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_EndPlayStory {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_EndPlayStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   題名なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_NonTitle {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_NonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語作成画面 -&gt; 提出作品管理画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_ShowStoryExplorer {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_ShowStoryExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語作成画面 -&gt; 作曲画面 (ページ %str1% 作曲開始) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_StartComposition {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_StartComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語作成画面 -&gt; 題名入力画面 (物語名入力開始) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_StartEntitle {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_StartEntitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語作成画面 -&gt; 文章入力画面 (ページ %str1% 文章入力開始) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_StartInputSentence {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_StartInputSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物語作成画面 -&gt; 物語再生画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_StartPlayStory {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_StartPlayStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作品提出 (ものがたりおんがく) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_Submit {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_Submit_Failure {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_Submit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_MakeStoryScr_Submit_Success {
            get {
                return ResourceManager.GetString("Msg_MakeStoryScr_Submit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルコピー開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopy {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %str1% -&gt; %str2% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopy_Path {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopy_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルコピー結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (コピー先が未設定) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult_Failure_DstEmpty {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult_Failure_DstEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (コピー先ルートディレクトリが存在しない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult_Failure_DstRootNotFound {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult_Failure_DstRootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (下記例外参照) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult_Failure_Exception {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult_Failure_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (コピー元ファイルが存在しない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult_Failure_SrcFileNotFound {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult_Failure_SrcFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_FileCopyResult_Success {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_FileCopyResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト名 / IP アドレスの取得失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_GetHostAddress_Failue {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_GetHostAddress_Failue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク接続状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_IsNetworkAvailable {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_IsNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用不可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_IsNetworkAvailable_False {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_IsNetworkAvailable_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用可能 - %str1% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NetworkMgr_IsNetworkAvailable_True {
            get {
                return ResourceManager.GetString("Msg_NetworkMgr_IsNetworkAvailable_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽譜データ 自動保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_OneScr_AutoSave {
            get {
                return ResourceManager.GetString("Msg_OneScr_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動保存データ削除 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_OneScr_AutoSaveFileDelete_Failure {
            get {
                return ResourceManager.GetString("Msg_OneScr_AutoSaveFileDelete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_PrintMgr_PrintEnd {
            get {
                return ResourceManager.GetString("Msg_PrintMgr_PrintEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_PrintMgr_Printing {
            get {
                return ResourceManager.GetString("Msg_PrintMgr_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ : %str1% / %str2% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_PrintMgr_Printing_Page {
            get {
                return ResourceManager.GetString("Msg_PrintMgr_Printing_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_PrintMgr_PrintStart {
            get {
                return ResourceManager.GetString("Msg_PrintMgr_PrintStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用プリンタ : %str1% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_PrintMgr_PrintStart_PrinterName {
            get {
                return ResourceManager.GetString("Msg_PrintMgr_PrintStart_PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DirectX -DirectSound デバイス生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SoundMgr_CreateDevice {
            get {
                return ResourceManager.GetString("Msg_SoundMgr_CreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 (サウンドデバイスがインストールされていない等の原因により、muphic を起動できませんでした) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SoundMgr_CreateDevice_Failure {
            get {
                return ResourceManager.GetString("Msg_SoundMgr_CreateDevice_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先強調レベル設定 (推奨される設定です) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SoundMgr_CreateDevice_Priority {
            get {
                return ResourceManager.GetString("Msg_SoundMgr_CreateDevice_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム環境 (Graphic Adaptor) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SysInfoMgr_GetAdapterInfo {
            get {
                return ResourceManager.GetString("Msg_SysInfoMgr_GetAdapterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用可能な物理メモリ (空き) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SysInfoMgr_GetAvailableMemorySize {
            get {
                return ResourceManager.GetString("Msg_SysInfoMgr_GetAvailableMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用可能な物理メモリ (最大) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SysInfoMgr_GetTotalMemorySize {
            get {
                return ResourceManager.GetString("Msg_SysInfoMgr_GetTotalMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム環境 (Operating System) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_SysInfoMgr_GetWindowsInfo {
            get {
                return ResourceManager.GetString("Msg_SysInfoMgr_GetWindowsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ”おわり”ボタン (プログラム終了) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TopScr_Click_EndButton {
            get {
                return ResourceManager.GetString("Msg_TopScr_Click_EndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひとりでおんがくモード -&gt; トップ画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TopScr_EndOneScreen {
            get {
                return ResourceManager.GetString("Msg_TopScr_EndOneScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ものがたりおんがくモード -&gt; トップ画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TopScr_EndStoryScreen {
            get {
                return ResourceManager.GetString("Msg_TopScr_EndStoryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップ画面 -&gt; ひとりでおんがくモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TopScr_StartOneScreen {
            get {
                return ResourceManager.GetString("Msg_TopScr_StartOneScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップ画面 -&gt; ものがたりおんがくモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_TopScr_StartStoryScreen {
            get {
                return ResourceManager.GetString("Msg_TopScr_StartStoryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML 読込 / 逆シリアル化 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileReader_Deserialize_Failure {
            get {
                return ResourceManager.GetString("Msg_XmlFileReader_Deserialize_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML 読込 / 逆シリアル化 成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileReader_Deserialize_Success {
            get {
                return ResourceManager.GetString("Msg_XmlFileReader_Deserialize_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ読込 失敗 (ファイルが存在しない) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileReader_FileNotFound {
            get {
                return ResourceManager.GetString("Msg_XmlFileReader_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル一覧取得 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileReader_GetFileList_Failure {
            get {
                return ResourceManager.GetString("Msg_XmlFileReader_GetFileList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先のディレクトリ生成失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileWriter_CreateDirectoryFailure {
            get {
                return ResourceManager.GetString("Msg_XmlFileWriter_CreateDirectoryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先のディレクトリ生成失敗 (パス名が長すぎる) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileWriter_CreateDirectoryFailure_PathTooLong {
            get {
                return ResourceManager.GetString("Msg_XmlFileWriter_CreateDirectoryFailure_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML ファイル生成 / 保存 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileWriter_FileWrite_Failure {
            get {
                return ResourceManager.GetString("Msg_XmlFileWriter_FileWrite_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML シリアル化 失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileWriter_Serialize_Failure {
            get {
                return ResourceManager.GetString("Msg_XmlFileWriter_Serialize_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML シリアル化 / 保存 成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_XmlFileWriter_Serialize_Success {
            get {
                return ResourceManager.GetString("Msg_XmlFileWriter_Serialize_Success", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon muphic {
            get {
                object obj = ResourceManager.GetObject("muphic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
